development:
  adapter: postgresql
  host: localhost
  database: datatreff
  pool: 5
  timeout: 5000
  username: datatreff
  password: 'datatreff'

#production:
#  adapter: postgresql
#  host: localhost
#  database:
#  username:
#  password:
#  pool: 5
#  timeout: 5000
